### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by karimnyumba** [karimnyumba/chatafisha_final#11]
Put appropriate hooks: Stylish hook design

**Comment by karimnyumba** [comment]
@widambeDeograss can you work on this, maybe find appropriate hooks for loading rather than just displaying the word 'loafing'

**Comment by fierylion** [comment]
Hello @widambeDeograss Please try to use useReducer hook and useContext hook to manage ur states, It is a best practice especially on our bog project. Please also try to minimize importing of components by using index.js file to make multiple exports.

**Comment by widambeDeograss** [comment]
@fierylion got u brother
