### ISSUE TITLE
Issue with navbar

### ISSUE THREAD

**Issue by fierylion** [karimnyumba/chatafisha_final#3]
The **news_and_updates** page navbar is not responsive. 

I would suggest the navbar to be a single component inorder to reuse in each and every page, What do you think @karimnyumba

**Comment by karimnyumba** [comment]
Navbar component created, but collapse functionality doesn't work. Also the integrate the Navbar component with the pages @widambeDeograss

**Comment by widambeDeograss** [comment]
Navbar component complete
